---
# Source: web/templates/configmap-nginx.yaml
kind:           ConfigMap
apiVersion:     v1         
metadata:
    name:       configuracion-nginx
data:
    default.conf: |
        server {
            listen       80;
            listen  [::]:80;
            server_name  localhost;
        
            #access_log  /var/log/nginx/host.access.log  main;
        
            location / {
                root   /miweb;
                index  index.html index.htm;
            }
            
            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /miweb;
            }
        
        }
---
# Source: web/templates/configmap-scripts.yaml
kind:           ConfigMap
apiVersion:     v1         
metadata:
    name:       scripts

data:
    cargador.sh: |
        #!/bin/bash
        if [[ ! -f /misitioWeb/index.html ]]; then 
            apt-get update && apt-get install git -y
            git clone $REPO_URL /misitioWeb
        fi
---
# Source: web/templates/configmap-web.yaml
kind:           ConfigMap
apiVersion:     v1         
metadata:
    name:       web
data:
    URL:        https://github.com/IvanciniGT/webEjemploAnsible
---
# Source: web/templates/pvc.yaml
kind:           PersistentVolumeClaim
apiVersion:     v1          

metadata:
    name:       peticion-volumen-mi-web
    
spec:
    resources:
        requests:
            storage: 10Gi
    # Tipo
    storageClassName: cluster-nfs-ivan
    accessModes:
        - ReadWriteOnce
---
# Source: web/templates/service.yaml
kind:           Service
apiVersion:     v1          

metadata:
    name:       nginx 
    
spec:
    type: NodePort 
    ports:
        - port: 80
          targetPort: 80
          protocol: TCP
    selector:
        app: nginx
---
# Source: web/templates/deployment.yaml
kind:                                   Deployment   
apiVersion:                             apps/v1         
metadata:
    name:                               deployment-nginx

spec:
    replicas: 2
    selector:
        matchLabels:
            app:                        nginx          
    template:
        metadata:
            name:                       template-pod-nginx
            labels:
                app:                    nginx   
                autor:                  ivan
        spec:
        
        
            affinity: 
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution: 
                        nodeSelectorTerms: 
                            - matchExpressions:
                                - key: tipo
                                  operator: In   
                                  values:
                                    - servidor-web
                podAntiAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution: 
                        - labelSelector:  
                            matchExpressions:
                                - key: autor
                                  operator: In
                                  values:
                                    - ivan
                          topologyKey: kubernetes.io/hostname
            volumes:
                -   name:               scripts
                    configMap:
                        name:           scripts
                        defaultMode:    0777
                -   name:               configuracion-nginx
                    configMap:
                        name:           configuracion-nginx
                -   name:               volumen-web
                    #emptyDir:           {}
                    persistentVolumeClaim:
                        claimName:      peticion-volumen-mi-web
            initContainers:
                -   name:               cargador-web
                    image:              ubuntu:latest
                    command:
                                        - sh
                                        - -c 
                                        - /scripts/cargador.sh
                    env:
                        - name:         REPO_URL
                          valueFrom:
                            configMapKeyRef:
                                name:   web
                                key:    URL
                    volumeMounts:
                        - name:         scripts
                          mountPath:    /scripts
                        - name:         volumen-web
                          mountPath:    /misitioWeb
            containers:
                - # Contenedor nginx
                    name:               nginx
                    image:              nginx:latest
                    ports:
                        - containerPort: 80
                    volumeMounts:
                        - name:         volumen-web
                          mountPath:    /miweb
                        - name:         configuracion-nginx
                          mountPath:   /etc/nginx/conf.d
