kind:           Namespace   
apiVersion:     v1          

metadata:
    name:       wp-prod



---
kind:           ConfigMap   
apiVersion:     v1          

metadata:
    name:       configuracion
    namespace:  wp-prod

    
data:
    MYSQL_RANDOM_ROOT_PASSWORD: "1"
    MYSQL_USER: usuarioprod
    MYSQL_DATABASE: miweb



---
kind:           Secret   
apiVersion:     v1          

metadata:
    name:       secretos
    namespace:  wp-prod
    
data:   # Los valores van en base64
    password: cGFzc3dvcmQ=



---
kind:           PersistentVolume
apiVersion:     v1          

metadata:
    name:       volumen-wp-1
    
spec:
    capacity: 
        storage: 20Gi 
    storageClassName: rapidito-redundante
    accessModes:
        - ReadWriteOnce
        - ReadWriteMany
        - ReadOnlyMany
    hostPath:    # PARA JUGAR
        path: /home/ubuntu/environment/datos/wp1
        type: DirectoryOrCreate 
        
        
        
---
kind:           PersistentVolume
apiVersion:     v1          

metadata:
    name:       volumen-wp-2
    
spec:
    capacity: 
        storage: 20Gi 
    storageClassName: rapidito-redundante
    accessModes:
        - ReadWriteOnce
        - ReadWriteMany
        - ReadOnlyMany
    hostPath:    # PARA JUGAR
        path: /home/ubuntu/environment/datos/wp2
        type: DirectoryOrCreate 