
kind:           PersistentVolumeClaim
apiVersion:     v1          

metadata:
    name:       peticion-volumen-wp
    
spec:
    resources:
        requests:
            storage: 10Gi # Tamaño que necesito
    # Tipo
    storageClassName: rapidito-redundante
    accessModes:
        - ReadWriteOnce
---
kind:           PersistentVolumeClaim
apiVersion:     v1          

metadata:
    name:       peticion-volumen-mysql
    
spec:
    resources:
        requests:
            storage: 10Gi # Tamaño que necesito
    # Tipo
    storageClassName: rapidito-redundante
    accessModes:
        - ReadWriteOnce
---
kind:           Service
apiVersion:     v1          

metadata:
    name:       wp  
    
spec:
    type: NodePort
    ports:
        - port: 80          # Puerto en IP del servicio
          targetPort: 80    # Puerto en los contenedores
          #protocol: TCP
          #nodePort: 30080
    
    selector:
        app: wordpress
        
---
kind:           Service
apiVersion:     v1          

metadata:
    name:       db  
    
spec:
    type: ClusterIP
    ports:
        - port: 3306         
          targetPort: 3306   

    selector:
        app: mysql
        
---
kind:           Deployment   
apiVersion:     apps/v1         
                
metadata:
    name:       wordpress

spec:
    replicas: 1
    
    selector:
        matchLabels:
            app: wordpress          #******************
    
    template:
        metadata:
            name:       template-wordpress
            #namespace:   mi-servidor-web    No lo hacemos
            labels:
                app:    wordpress   #******************
        
        spec:
            volumes:
                - name: persistente
                  persistentVolumeClaim: 
                    claimName: peticion-volumen-wp
            containers:
                - # Contenedor nginx
                    name:   wordpress
                    image:  wordpress:latest
                    volumeMounts:
                        - name: persistente
                          mountPath: /var/www/html
                    env:
                        - name: WORDPRESS_DB_HOST
                          value: db
                          
                        - name: WORDPRESS_DB_USER
                          valueFrom:
                            configMapKeyRef:
                                name: configuracion
                                key:  MYSQL_USER
                        - name: WORDPRESS_DB_PASSWORD
                          valueFrom:
                            secretKeyRef:
                                name: secretos
                                key:  password
                        - name: WORDPRESS_DB_NAME
                          valueFrom:
                            configMapKeyRef:
                                name: configuracion
                                key:  MYSQL_DATABASE
                    ports:
                        - containerPort: 80
                        
---
kind:           Deployment   
apiVersion:     apps/v1         
                
metadata:
    name:       mysql

spec:
    replicas: 1
    
    selector:
        matchLabels:
            app: mysql          #******************
    
    template:
        metadata:
            name:       template-mysql
            #namespace:   mi-servidor-web    No lo hacemos
            labels:
                app:    mysql   #******************
        
        spec:
            volumes:
                - name: persistente
                  persistentVolumeClaim: 
                    claimName: peticion-volumen-mysql
            containers:
                - # Contenedor nginx
                    name:   mysql
                    image:  mysql:5.7
                    volumeMounts:
                        - name: persistente
                          mountPath: /var/lib/mysql
                    envFrom:
                        - configMapRef:
                            name: configuracion
                    env:
                        - name: MYSQL_PASSWORD
                          valueFrom:
                            secretKeyRef:
                                name: secretos
                                key:  password
                    ports:
                        - containerPort: 3306
