
---
kind:           ConfigMap
apiVersion:     v1         
metadata:
    name:       script-recarga

data:
    recargador.sh: |
        #!/bin/bash
    
        apt-get update && apt-get install git -y
        cd /misitioWeb
        git pull
---
kind:           Job
apiVersion:     batch/v1


kind:           CronJob
apiVersion:     batch/v1

metadata:
    name:       actualizador-web

spec:
    schedule: "2 * * * *"
    jobTemplate:
        spec:
            template:
                spec:
                    restartPolicy:              Never
                    volumes:
                        -   name:               scripts
                            configMap:
                                name:           script-recarga
                                defaultMode:    0777
                        -   name:               volumen-web
                            persistentVolumeClaim:
                                claimName:      peticion-volumen-mi-web
                    containers:
                        -   name:               cargador-web
                            image:              ubuntu:latest
                            command:
                                                - sh
                                                - -c 
                                                - /scripts/recargador.sh
                            volumeMounts:
                                - name:         scripts
                                  mountPath:    /scripts
                                - name:         volumen-web
                                  mountPath:    /misitioWeb
