kind:           HorizontalPodAutoscaler
apiVersion:     autoscaling/v1          

metadata:
    name:       nginx-hpa
    
spec: 
    scaleTargetRef:
        kind:           Deployment   
        apiVersion:     apps/v1         
        name:           deployment-nginx
        
    minReplicas:        1
    maxReplicas:        10
    
    # En base a qué escalo
    targetCPUUtilizationPercentage: 50
    
    
