kind:           Deployment   
apiVersion:     apps/v1         
metadata:
    name:       deployment-nginx

spec:
    replicas: 1
    selector:
        matchLabels:
            app: nginx          
    template:
        metadata:
            name:       template-pod-nginx
            labels:
                app:    nginx   
        spec:
            containers:
                - # Contenedor nginx
                    name:   nginx
                    image:  nginx:latest
                    ports:
                        - containerPort: 80
---
kind:           Service
apiVersion:     v1          

metadata:
    name:       nginx 
    
spec:
    type: NodePort 
    ports:
        - port: 80
          targetPort: 80
          protocol: TCP
          nodePort: 30080
    selector:
        app: nginx